version: "3.7"
services:
  application-backend:
    build: application-backend
    ports:
      - 8080:8080

  application-frontend:
    image: nginx
    volumes:
      - ./application-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./application-frontend/index.html:/usr/share/nginx/html/index.html
    ports:
      - 4200:80

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:7.4.5-ubuntu
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug

    links:
      - prometheus

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081:8081

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100