on: push
name: Build and tests
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: gradle clean assemble

      - name: Tests
        run: gradle test

      - name: Mutation tests
        run: gradle :application-backend:pitest

      - name: Report unit tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests
          path: '**/build/test-results/test/TEST-*.xml'
          reporter: java-junit
          fail-on-error: true

      - name: Report mutation tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Mutation Tests
          path: '**/reports/pitest/**/mutations.xml'
          reporter: java-junit
          fail-on-error: true